### ISSUE TITLE
Typo fix AUC = 0 represents a model that is always wrong

### ISSUE THREAD

**Issue by tiagochst** [lgatto/IntroMachineLearningWithR#6]
Hi,

I think there is a typo error. 

it says AUC = 1 is a perfect model and also represents a model that is always wrong

<img width="1063" alt="Screen Shot 2019-04-24 at 11 18 56 AM" src="https://user-images.githubusercontent.com/145529/56666805-f2650880-6682-11e9-8228-b584e00d55de.png">

**Comment by lgatto** [comment]
Of course, thank you. Will fix it right away.
